In [33]:
import torch
import torch.nn as nn




In [34]:
a = torch.tensor([1e-10, 1e-10, 1e-10])
b = torch.tensor([1e-10, 1e-10, 1e-10])

In [35]:
c = torch.ones(3)
d = torch.zeros(3)
infy = c/(a*b*d)

In [36]:
result = torch.tensor([0.0, 0.0, 0.0]) / torch.tensor([0.0, 0.0, 0.0])
nany = (a*a*a*a*a*a*a*a*a*a*a*a*a*a*a)/(b*b*b*b*b*b*b*b*b*b*b*b)
nany

tensor([nan, nan, nan])

In [37]:
inf_a = torch.tensor([float('inf'), float('inf'), float('inf')])
inf_b = torch.tensor([float('inf'), float('inf'), float('inf')])
infy = inf_a/inf_b
infy

tensor([nan, nan, nan])

In [46]:
zero_a = torch.tensor([0.0, 0.0, 0.0])
zero_b = torch.tensor([0.0, 0.0, 0.0])

# nan_Case1
nan_case1 = zero_a/zero_b

# nan_Case2
nan_case2 = zero_a/inf_b # this is zero

# nan_Case3
nan_case3 = inf_a/zero_b
nan_case3 # this is inf

# nan_case4
nan_case4 = inf_a/inf_b
nan_case4 # this is nan


tensor([nan, nan, nan])