In [1]:
import torch
import torch.nn as nn

n= 12
k= 12
weights = torch.randn(k, n)
input_tensor = torch.ones(15, n)
res_tensor = torch.Tensor([])

# For each element in input, multiply it by the corresponding weight, then sum them up
for row in weights:
    new_input = input_tensor * row # default is hadamard. 
    sum_result = torch.sum(new_input)
    res_tensor = torch.cat((res_tensor, sum_result.view(1)))
print(res_tensor)

tensor([  8.2936,  40.1806,  99.7651, -50.0500, -38.1479, -12.8715,  28.1121,
         33.2948, -14.1945, -85.4007, -25.4517,  69.8477])


In [2]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a*b)

tensor([ 4, 10, 18])


In [3]:
import torch
import torch.nn as nn

a = torch.tensor([[0.1,0.2,0.3],[0.4,0.5,0.6]])
# make 1,3 weighted linear layer
linear = nn.Linear(3,2) 
linear2 = nn.Linear(2,2)
linear3 = nn.Linear(2,1)
# assign a as a weight of linear layer
linear.weight = nn.Parameter(a)
print("Weights : ",linear.weight)
input_tensor = torch.ones(15, 3)
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# go through linear layer, get the gradient of a.
optimizer.zero_grad()
output = linear(input_tensor)
output = linear2(output)
output = linear3(output)
loss = torch.sum(output)
loss.backward()
print("grads of linear layer 1:\n", linear.weight.grad)
print("grads of linear layer 2:\n", linear2.weight.grad)
print("grads of linear layer 3:\n", linear3.weight.grad)

Weights :  Parameter containing:
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]], requires_grad=True)
grads of linear layer 1:
 tensor([[-4.2068, -4.2068, -4.2068],
        [ 2.4381,  2.4381,  2.4381]])
grads of linear layer 2:
 tensor([[  0.8907,   5.6621],
        [ -2.2406, -14.2431]])
grads of linear layer 3:
 tensor([[1.5191, 2.8220]])


In [4]:
a = torch.rand(5)
print(a.shape)
b = torch.sin(a)
print(b.shape)


torch.Size([5])
torch.Size([5])


In [5]:
tens = torch.Tensor([[0.2731, 0.0100, 0.0575, 0.0426, 0.0340, 0.1967, 0.6245, 0.0985, 0.0724],
        [0.0337, 0.1670, 0.0189, 0.0953, 0.1939, 0.0063, 0.0330, 0.0134, 0.1284],
        [0.1744, 0.0810, 0.3131, 0.0339, 0.1653, 0.0391, 0.0055, 0.2705, 0.0722],
        [0.0345, 0.1560, 0.0197, 0.0930, 0.2867, 0.0387, 0.1175, 0.0803, 0.0895],
        [0.1516, 0.2765, 0.1655, 0.0528, 0.0351, 0.2438, 0.0111, 0.1599, 0.0331],
        [0.0744, 0.0256, 0.0541, 0.1760, 0.0398, 0.1930, 0.1206, 0.1871, 0.0642],
        [0.1078, 0.1313, 0.1200, 0.3759, 0.0242, 0.0985, 0.0121, 0.1075, 0.3076],
        [0.0853, 0.0651, 0.0350, 0.1003, 0.0356, 0.1779, 0.0586, 0.0081, 0.1397],
        [0.0652, 0.0875, 0.2161, 0.0303, 0.1854, 0.0060, 0.0170, 0.0747, 0.0929]])


for trial in range(5):
    tens = nn.functional.softmax(tens, dim=0)
    print(tens)

tensor([[0.1303, 0.1001, 0.1048, 0.1032, 0.1024, 0.1206, 0.1820, 0.1094, 0.1066],
        [0.1026, 0.1171, 0.1008, 0.1088, 0.1202, 0.0997, 0.1007, 0.1004, 0.1127],
        [0.1180, 0.1075, 0.1353, 0.1023, 0.1168, 0.1030, 0.0980, 0.1299, 0.1065],
        [0.1026, 0.1159, 0.1009, 0.1085, 0.1319, 0.1030, 0.1096, 0.1074, 0.1084],
        [0.1154, 0.1307, 0.1168, 0.1042, 0.1025, 0.1264, 0.0986, 0.1163, 0.1025],
        [0.1068, 0.1017, 0.1045, 0.1179, 0.1030, 0.1201, 0.1100, 0.1195, 0.1057],
        [0.1104, 0.1130, 0.1116, 0.1440, 0.1014, 0.1093, 0.0987, 0.1104, 0.1348],
        [0.1080, 0.1058, 0.1025, 0.1093, 0.1026, 0.1183, 0.1033, 0.0999, 0.1140],
        [0.1058, 0.1082, 0.1228, 0.1019, 0.1192, 0.0996, 0.0991, 0.1068, 0.1088]])
tensor([[0.1133, 0.1099, 0.1104, 0.1102, 0.1101, 0.1122, 0.1192, 0.1109, 0.1106],
        [0.1102, 0.1118, 0.1100, 0.1108, 0.1121, 0.1098, 0.1099, 0.1099, 0.1113],
        [0.1119, 0.1107, 0.1138, 0.1101, 0.1117, 0.1102, 0.1096, 0.1132, 0.1106],
        [0.1102

In [6]:
tens = nn.functional.softmax(tens, dim=1)
tens

tensor([[0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111]])

In [7]:
tens = nn.functional.softmax(tens, dim=1)
tens

tensor([[0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111]])

In [8]:
SEED = 7992
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED) # if you are using multi-GPU.
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True

In [9]:
# random seed test 
a = torch.rand(5)
print(a)

b = torch.rand(5)
print(b)

tensor([0.1200, 0.0215, 0.8142, 0.2947, 0.1395])
tensor([0.3831, 0.8640, 0.0267, 0.2292, 0.2779])


In [10]:
import torch 
import torch.nn as nn

a = torch.Tensor([1,2,3,4])
b = torch.Tensor([1,2,3,4])
c = torch.Tensor([1,2,3,4])

d = nn.ParameterList([nn.Parameter(a), nn.Parameter(b), nn.Parameter(c)])

# softmax them.
for i in range(len(d)):
    d[i] = nn.functional.softmax(d[i], dim=0)
    print(d[i])

Parameter containing:
tensor([0.0321, 0.0871, 0.2369, 0.6439], requires_grad=True)
Parameter containing:
tensor([0.0321, 0.0871, 0.2369, 0.6439], requires_grad=True)
Parameter containing:
tensor([0.0321, 0.0871, 0.2369, 0.6439], requires_grad=True)


In [13]:
from torchvision import transforms

a= torch.ones(3,128,128)
# resize
tr = transforms.Resize(32)
b = tr(a) 
print(a.shape,b.shape)

torch.Size([3, 128, 128]) torch.Size([3, 32, 32])


In [27]:
# original 3, 320, 512
a = torch.ones(3,320,512)

# target : 4,64,64.
c_mean = torch.mean(a, dim=(0))
# additional channel for fourth channel
c_mean = c_mean.unsqueeze(0)
# attach
res = torch.cat([a, c_mean])
print(res.shape)

# resize
tr = transforms.Resize((64,64))
b = tr(res)
print(a.shape,res.shape,b.shape)

torch.Size([4, 320, 512])
torch.Size([3, 320, 512]) torch.Size([4, 320, 512]) torch.Size([4, 64, 64])
